package main

const (
	filetemplate = `// Copyright {{.Year}} ExoAplha. All rights reserved.
// Code generated by goconvres({{.Version}})
// THIS FILE HAS BEEN AUTOGENERATED, DO NOT EDIT OR MODIFY !
//
// Generated on {{.DateTime}}

package {{.Package}}

var (
	// {{.Name}} generated resource from file "{{.FileName}}".
	{{.Name}} = []byte{
{{.Content}}
	}
)
`
)
