package main

const (
	filetemplate = `// Code generated by goconvres({{.Version}})
// THIS FILE HAS BEEN AUTOMATICALLY GENERATED, DO NOT EDIT OR MODIFY !
//
// Generated on {{.DateTime}}

package {{.Package}}

var (
	// {{.Name}} generated resource from file "{{.FileName}}".
	{{.Name}} = []byte{
{{.Content}}
	}
)
`
)
